config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'films#index'
  resources :films do
    member do
      post :favor
      post :dislike
    end
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :reviews
  belongs_to :user
  validates :title, presence: true
  has_many :film_relationships
  has_many :members, through: :film_relationships, source: :user
end

app/models/film_relationship.rb
class FilmRelationship < ApplicationRecord
  belongs_to :film
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :film

  validates :content, presence: true
  scope :recent, -> { order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :films
  has_many :reviews
  has_many :film_relationships
  has_many :favored_films, :through => :film_relationships, :source => :film

  def is_favored?(film)
    favored_films.include?(film)
  end

  def favor!(film)
    favored_films << film
  end

  def dislike!(film)
    favored_films.delete(film)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
before_action :authenticate_user! , only: [:new, :create, :edit, :destroy, :update]
before_action :find_film_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @films = Film.all
  end

  def show
    @film = Film.find(params[:id])
    @reviews = @film.reviews.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(film_params)
    @film.user = current_user
    if @film.save
      current_user.favor!(@film)
      redirect_to films_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @film.update(film_params)
      redirect_to films_path, notice:"更新成功"
    else
      render :edit
    end
   end

  def destroy
    @film.destroy
    redirect_to films_path, alert:"删除成功"
  end

  def favor
    @film = Film.find(params[:id])

    if !current_user.is_favored?(@film)
      current_user.favor!(@film)
      flash[:notice] = "收藏成功!"
    else
      flash[:warning] = "你已经收藏了！"
    end

    redirect_to film_path(@film)
  end

  def dislike
    @film = Film.find(params[:id])

    if current_user.is_favored?(@film)
      current_user.dislike!(@film)
      flash[:alert] = "已经取消收藏！"
    else
      flash[:warning] = "你还没有收藏！"
    end

    redirect_to film_path(@film)

  end

  private

  def find_film_and_check_permission
    @film = Film.find(params[:id])
    if current_user != @film.user
      redirect_to root_path, alert: "You have no permission."
    end
  end

  def film_params
    params.require(:film).permit(:title, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :authenticate_user! , only: [:new, :create, :edit, :destroy, :update]

  def new
    @film = Film.find(params[:film_id])
    @review = Review.new
  end

  def create
    @film = Film.find(params[:film_id])
    @review = Review.new(review_params)
    @review.film = @film
    @review.user = current_user

    if @review.save
      redirect_to film_path(@film)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
  def render_film_description(film)
      simple_format(film.description)
    end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 BigOrange
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Movie Reviews</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登录", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/films/_form.html.erb
<%= simple_form_for @film do |f| %>
  <div class="form-film">
    <%= f.input :title,  input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/films/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑影片</h2>

  <hr>

  <%= render "form" %>

</div>

app/views/films/index.html.erb
<div class="col-md-12">
  <div class="film">
    <%= link_to("New movie", new_film_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>电影名</td>
        <td>简介</td>
      </tr>
    </thead>

    <tbody>
      <% @films.each do |film| %>
        <tr>
          <td>#</td>
          <td><%= link_to(film.title, film_path(film)) %></td>
          <td><%= film.description %></td>
          <td>
             <% if current_user && current_user == film.user %>
              <%= link_to("Edit", edit_film_path(film), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", film_path(film),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
             <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/films/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增影片</h2>

  <hr>

  <%= render "form" %>

</div>

app/views/films/show.html.erb
<div class="col-md-12">
  <div class="film">
    <% if current_user && current_user == @film.user %>
      <%= link_to("Edit", edit_film_path(@film), class: "btn btn-primary pull-right")%>
    <% end %>
  </div>
  <span class="pull-right">
  <% if current_user && current_user.is_favored?(@film) %>
    <label class="label label-success"> 已收藏 </label>
    <%= link_to("取消收藏", dislike_film_path(@film), method: :post, class: "btn btn-default") %>
    <%= link_to("写点评", new_film_review_path(@film), class: "btn btn-default pull-right")%>
  <% else %>
    <label class="label label-warning"> 收藏后评论 </label>
    <%= link_to("收藏",  favor_film_path(@film), method: :post, class: "btn btn-default") %>
  <% end %>

</span>
  <h2><%= @film.title %></h2>
  <p><%= @film.description %></p>
  <table class="table">
  <thead>
    <tr>
      <th>影评内容</th>
      <th>发表者</th>
      <th>发表时间</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
    <tr>
      <td><%= review.content %></td>
      <td><%= review.user.email %></td>
      <td><%= review.created_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>
    <div class="text-center">
      <%= will_paginate @reviews %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
           <%= render "common/navbar" %>
           <%= render "common/flashes" %>
           <%= yield %>
       </div>

       <%= render "common/footer" %>

  </body>
</html>

app/views/reviews/new.html.erb
<h2 class="text-center">新影评</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@film,@review] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control" } %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>